//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_teste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        public int ID_CLI { get; set; }
        public string Nome_CLI { get; set; }
        public string Endereco_CLI { get; set; }
        public string Numero_CLI { get; set; }
        public string Bairro_CLI { get; set; }
        public string Cidade_CLI { get; set; }
        public string UF_Cli { get; set; }
        public string CEP_Cli { get; set; }
        public string Telefone_CLI { get; set; }
    }
}
